In [1]:
# Introduction

# In the previous project, we compared the accuracies by training 
# the classifier on different classification models 
# (like Logistic Regression, SVM etc.). In this project, we will be 
# evaluating model performance using XG Boost on the 'Stroke Prediction Dataset'
# from kaggle.

# Importing basic libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

df = pd.read_csv('../input/stroke-prediction-dataset/healthcare-dataset-stroke-data.csv');

# This shows the first five rows for all the features of the dataset

df.head()

# We want to keep all the categorical features (like 'gender', 'ever_married' etc)
# in the beginning 

df = df[['id', 'gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status',
         'hypertension', 'stroke', 'age', 'avg_glucose_level', 'bmi', 'heart_disease']]

# This shows the feature 'heart_disease' consists of two values 1 and 0

print(df['heart_disease'].unique())

# We neglect the 'id' feature
# 'X' consists of independent variables
# 'y' consists of dependent variable

X = df.iloc[:, 1:11].values
y = df.iloc[:, -1].values

# This shows a list of features that consist of null values

print(df.columns[df[df.columns].isnull().sum() != 0])

# Replacing the null value for that feature with 
# the mean of all other values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, [9]])
X[:, [9]] = imputer.transform(X[:, [9]])

# Encoding categorical data

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1, 2, 3, 4])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

print(y)

# Splitting the dataset into training set and test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

print(y_train)

print(y_test)

# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 18:21] = sc.fit_transform(X_train[:, 18:21])
X_test[:, 18:21] = sc.transform(X_test[:, 18:21])

# Training the classifier with XG Boost

from xgboost import XGBClassifier
classifier = XGBClassifier(use_label_encoder=False, eval_metric="logloss")
classifier.fit(X_train, y_train)

# Finding the predictions of each model

y_pred = classifier.predict(X_test)

# Finding the accuracy of each model

from sklearn.metrics import accuracy_score

print("XG Boost - " , accuracy_score(y_test, y_pred))

# Conclusion

# So we observe that accuracy turns out to be
# 94.2% when the classifier is trained with xg boost
# However, we got a better accuracy of 94.7% 
# in the previous exercise when we 
# used Logistic Regression, SVM, and Kernel SVM.

[1 0]
Index(['bmi'], dtype='object')
[[0.0 1.0 0.0 ... 67.0 228.69 36.6]
 [1.0 0.0 0.0 ... 61.0 202.21 28.893236911794666]
 [0.0 1.0 0.0 ... 80.0 105.92 32.5]
 ...
 [1.0 0.0 0.0 ... 35.0 82.99 30.6]
 [0.0 1.0 0.0 ... 51.0 166.29 25.6]
 [1.0 0.0 0.0 ... 44.0 85.28 26.2]]
[1 0 1 ... 0 0 0]
[0 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
XG Boost -  0.9420970266040689
